apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLbXArbGJhYzhEd09UVHdHZ3ZDCk80Ukw0eU92dHBhM2pyWjJ5KzYzUHNqeTZtNGpHelBqVXZqWXltQkJibi96c0ROUHRQdHhwY2E3NEFmMU9pYXAKaUExRzBsVURqRlNETlZXU2c3NHl1Zk5LODBTQjRUUXVFcmlpVnM0WTI0dVVGaCtQSWN1eUwrbjJuSjdEM0JxQwpzT1JueUdHZ2VseUpXc1YwUnlNOTdURTFqcjY2RlJLWnFYZ2U1STliK2Rkend4Sm5JVkxwQUplenJGaHdaZjY1CkdaRDFOYXpybVlSV3Vta3dMVVU2ajlnRWZ3RnhUMFRodXBqVGEyV1l1VFZXYW1mZWlUQW40ZG9XK09icjhoN0MKRHI1NEFoaGl3TVhuUzVNTmNSNzlhdU1RbjY5ZGpYaG5FUlJQVDhDNjhqQllBQXlMQmFVakdNazE1SHlDbkhPZwpsSnNDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJEQXQyWk5pYzM2Q0plNElXOGtBL09wakhrCmQ3QjNSODI4NFl0VXZYWW5xamN4ekFRSHdJM0NTWm8zcEkwWlNqK0JGL0duVmFjeUZaNlRwYlQ2NDRXYlFLTisKUS9lMjdlY3ZESGhUMGRZaklueTZQVFFIV0F4c0M3RXVvc3o1RzlhMDYwbjA1Wmd6WFRlVE50VGRSRGMvcldocApVeUJUalgrUEVjMzlXL3UwMzY5V2FCY2I2SmhvT2VqM2lhWlpHbEd3M2g4MjZwOTcwYjBhQU5QQ3YzbmR2Vk94CnlsVmxtMUpIc0VOTXlyQlUrWGowWnkyVEE2VldZNkh4d05EbmcxWEJpUEpMd1p5YlZOZm9Pbi9CUnFpTTRPeEgKK0hiYWZpVjJzYXUxMTlSN3JpVHVKK3EvanZEbHlaZGJNS1FqS0xiVStkaGlERTNsSVF0dFBoVmo2WEVyCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - digital signature
    - key encipherment
    - client auth
